require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EstabelecimentosController do

  # This should return the minimal set of attributes required to create a valid
  # Estabelecimento. As you add validations to Estabelecimento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "CNPJ" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstabelecimentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all estabelecimentos as @estabelecimentos" do
      estabelecimento = Estabelecimento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:estabelecimentos).should eq([estabelecimento])
    end
  end

  describe "GET show" do
    it "assigns the requested estabelecimento as @estabelecimento" do
      estabelecimento = Estabelecimento.create! valid_attributes
      get :show, {:id => estabelecimento.to_param}, valid_session
      assigns(:estabelecimento).should eq(estabelecimento)
    end
  end

  describe "GET new" do
    it "assigns a new estabelecimento as @estabelecimento" do
      get :new, {}, valid_session
      assigns(:estabelecimento).should be_a_new(Estabelecimento)
    end
  end

  describe "GET edit" do
    it "assigns the requested estabelecimento as @estabelecimento" do
      estabelecimento = Estabelecimento.create! valid_attributes
      get :edit, {:id => estabelecimento.to_param}, valid_session
      assigns(:estabelecimento).should eq(estabelecimento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Estabelecimento" do
        expect {
          post :create, {:estabelecimento => valid_attributes}, valid_session
        }.to change(Estabelecimento, :count).by(1)
      end

      it "assigns a newly created estabelecimento as @estabelecimento" do
        post :create, {:estabelecimento => valid_attributes}, valid_session
        assigns(:estabelecimento).should be_a(Estabelecimento)
        assigns(:estabelecimento).should be_persisted
      end

      it "redirects to the created estabelecimento" do
        post :create, {:estabelecimento => valid_attributes}, valid_session
        response.should redirect_to(Estabelecimento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estabelecimento as @estabelecimento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estabelecimento.any_instance.stub(:save).and_return(false)
        post :create, {:estabelecimento => { "CNPJ" => "invalid value" }}, valid_session
        assigns(:estabelecimento).should be_a_new(Estabelecimento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estabelecimento.any_instance.stub(:save).and_return(false)
        post :create, {:estabelecimento => { "CNPJ" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested estabelecimento" do
        estabelecimento = Estabelecimento.create! valid_attributes
        # Assuming there are no other estabelecimentos in the database, this
        # specifies that the Estabelecimento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Estabelecimento.any_instance.should_receive(:update).with({ "CNPJ" => "MyString" })
        put :update, {:id => estabelecimento.to_param, :estabelecimento => { "CNPJ" => "MyString" }}, valid_session
      end

      it "assigns the requested estabelecimento as @estabelecimento" do
        estabelecimento = Estabelecimento.create! valid_attributes
        put :update, {:id => estabelecimento.to_param, :estabelecimento => valid_attributes}, valid_session
        assigns(:estabelecimento).should eq(estabelecimento)
      end

      it "redirects to the estabelecimento" do
        estabelecimento = Estabelecimento.create! valid_attributes
        put :update, {:id => estabelecimento.to_param, :estabelecimento => valid_attributes}, valid_session
        response.should redirect_to(estabelecimento)
      end
    end

    describe "with invalid params" do
      it "assigns the estabelecimento as @estabelecimento" do
        estabelecimento = Estabelecimento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estabelecimento.any_instance.stub(:save).and_return(false)
        put :update, {:id => estabelecimento.to_param, :estabelecimento => { "CNPJ" => "invalid value" }}, valid_session
        assigns(:estabelecimento).should eq(estabelecimento)
      end

      it "re-renders the 'edit' template" do
        estabelecimento = Estabelecimento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estabelecimento.any_instance.stub(:save).and_return(false)
        put :update, {:id => estabelecimento.to_param, :estabelecimento => { "CNPJ" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estabelecimento" do
      estabelecimento = Estabelecimento.create! valid_attributes
      expect {
        delete :destroy, {:id => estabelecimento.to_param}, valid_session
      }.to change(Estabelecimento, :count).by(-1)
    end

    it "redirects to the estabelecimentos list" do
      estabelecimento = Estabelecimento.create! valid_attributes
      delete :destroy, {:id => estabelecimento.to_param}, valid_session
      response.should redirect_to(estabelecimentos_url)
    end
  end

end
