require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IngressosController do

  # This should return the minimal set of attributes required to create a valid
  # Ingresso. As you add validations to Ingresso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Tipo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngressosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ingressos as @ingressos" do
      ingresso = Ingresso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ingressos).should eq([ingresso])
    end
  end

  describe "GET show" do
    it "assigns the requested ingresso as @ingresso" do
      ingresso = Ingresso.create! valid_attributes
      get :show, {:id => ingresso.to_param}, valid_session
      assigns(:ingresso).should eq(ingresso)
    end
  end

  describe "GET new" do
    it "assigns a new ingresso as @ingresso" do
      get :new, {}, valid_session
      assigns(:ingresso).should be_a_new(Ingresso)
    end
  end

  describe "GET edit" do
    it "assigns the requested ingresso as @ingresso" do
      ingresso = Ingresso.create! valid_attributes
      get :edit, {:id => ingresso.to_param}, valid_session
      assigns(:ingresso).should eq(ingresso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ingresso" do
        expect {
          post :create, {:ingresso => valid_attributes}, valid_session
        }.to change(Ingresso, :count).by(1)
      end

      it "assigns a newly created ingresso as @ingresso" do
        post :create, {:ingresso => valid_attributes}, valid_session
        assigns(:ingresso).should be_a(Ingresso)
        assigns(:ingresso).should be_persisted
      end

      it "redirects to the created ingresso" do
        post :create, {:ingresso => valid_attributes}, valid_session
        response.should redirect_to(Ingresso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ingresso as @ingresso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ingresso.any_instance.stub(:save).and_return(false)
        post :create, {:ingresso => { "Tipo" => "invalid value" }}, valid_session
        assigns(:ingresso).should be_a_new(Ingresso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ingresso.any_instance.stub(:save).and_return(false)
        post :create, {:ingresso => { "Tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ingresso" do
        ingresso = Ingresso.create! valid_attributes
        # Assuming there are no other ingressos in the database, this
        # specifies that the Ingresso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ingresso.any_instance.should_receive(:update).with({ "Tipo" => "MyString" })
        put :update, {:id => ingresso.to_param, :ingresso => { "Tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested ingresso as @ingresso" do
        ingresso = Ingresso.create! valid_attributes
        put :update, {:id => ingresso.to_param, :ingresso => valid_attributes}, valid_session
        assigns(:ingresso).should eq(ingresso)
      end

      it "redirects to the ingresso" do
        ingresso = Ingresso.create! valid_attributes
        put :update, {:id => ingresso.to_param, :ingresso => valid_attributes}, valid_session
        response.should redirect_to(ingresso)
      end
    end

    describe "with invalid params" do
      it "assigns the ingresso as @ingresso" do
        ingresso = Ingresso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ingresso.any_instance.stub(:save).and_return(false)
        put :update, {:id => ingresso.to_param, :ingresso => { "Tipo" => "invalid value" }}, valid_session
        assigns(:ingresso).should eq(ingresso)
      end

      it "re-renders the 'edit' template" do
        ingresso = Ingresso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ingresso.any_instance.stub(:save).and_return(false)
        put :update, {:id => ingresso.to_param, :ingresso => { "Tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ingresso" do
      ingresso = Ingresso.create! valid_attributes
      expect {
        delete :destroy, {:id => ingresso.to_param}, valid_session
      }.to change(Ingresso, :count).by(-1)
    end

    it "redirects to the ingressos list" do
      ingresso = Ingresso.create! valid_attributes
      delete :destroy, {:id => ingresso.to_param}, valid_session
      response.should redirect_to(ingressos_url)
    end
  end

end
